name: Deploy React Application
on:
  push:
    branches:
      - mern-ec2-docker-ssl
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      - name: Login to docker hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker Image
        run: docker build -t vishalhuneria/react-app --build-arg REACT_APP_NODE_ENV='production' --build-arg REACT_APP_SERVER_BASE_URL='${{ secrets.REACT_APP_SERVER_BASE_URL }}' .
      - name: Publish Image to docker hub
        run: docker push vishalhuneria/react-app:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull image from docker hub
        run: docker pull vishalhuneria/react-app:latest
      - name: Delete old container
        run: docker rm -f reactjs-app-container
      - name: Run Docker Container
        run: docker run -d -p 3000:80 --name reactjs-app-container vishalhuneria/react-app
